name: ceph_exporter

on:
  workflow_dispatch:
  push:
    branches:
      - ecx-*
  pull_request:
    branches:
      - ecx-*
env:
  VERSION: 4.1.3

jobs:
  docker-image:
    name: Build x86 and arm Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Docker image
        run: make package